// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sms.proto

package sms

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SmsRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsRequest) Reset()         { *m = SmsRequest{} }
func (m *SmsRequest) String() string { return proto.CompactTextString(m) }
func (*SmsRequest) ProtoMessage()    {}
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{0}
}
func (m *SmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsRequest.Unmarshal(m, b)
}
func (m *SmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsRequest.Marshal(b, m, deterministic)
}
func (m *SmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsRequest.Merge(m, src)
}
func (m *SmsRequest) XXX_Size() int {
	return xxx_messageInfo_SmsRequest.Size(m)
}
func (m *SmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsRequest proto.InternalMessageInfo

func (m *SmsRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SmsRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*SmsRequest)(nil), "staffjoy.sms.SmsRequest")
}

func init() { proto.RegisterFile("sms.proto", fileDescriptor_c8d8bdc537111860) }

var fileDescriptor_c8d8bdc537111860 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0xce, 0x2d, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0x2e, 0x49, 0x4c, 0x4b, 0xcb, 0xca, 0xaf, 0xd4,
	0x2b, 0xce, 0x2d, 0x96, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xcb, 0x25, 0x95,
	0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54, 0x42, 0x94, 0x2a, 0x19, 0x70, 0x71, 0x05, 0xe7, 0x16,
	0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x95, 0xe4, 0x4b, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x31, 0x95, 0xe4, 0x0b, 0x09, 0x71, 0xb1, 0x24, 0xe5, 0xa7, 0x54, 0x4a,
	0x30, 0x81, 0x45, 0xc0, 0x6c, 0x23, 0x5f, 0xb0, 0x8e, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54,
	0x21, 0x7b, 0x2e, 0xce, 0xc0, 0xd2, 0xd4, 0xd2, 0xd4, 0xe0, 0xd4, 0xbc, 0x14, 0x21, 0x09, 0x3d,
	0x64, 0x8b, 0xf5, 0x10, 0x06, 0x4b, 0x89, 0xe9, 0x41, 0x1c, 0xa1, 0x07, 0x73, 0x84, 0x9e, 0x2b,
	0xc8, 0x11, 0x4a, 0x0c, 0x4e, 0xa2, 0x51, 0xc2, 0x65, 0x46, 0x08, 0x7d, 0xc9, 0xf9, 0xb9, 0xfa,
	0xc5, 0xb9, 0xc5, 0x49, 0x6c, 0x60, 0x85, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xc6,
	0xaf, 0x17, 0xd6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmsServiceClient is the client API for SmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsServiceClient interface {
	QueueSend(ctx context.Context, in *SmsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type smsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSmsServiceClient(cc *grpc.ClientConn) SmsServiceClient {
	return &smsServiceClient{cc}
}

func (c *smsServiceClient) QueueSend(ctx context.Context, in *SmsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/staffjoy.sms.SmsService/QueueSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServiceServer is the server API for SmsService service.
type SmsServiceServer interface {
	QueueSend(context.Context, *SmsRequest) (*empty.Empty, error)
}

// UnimplementedSmsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSmsServiceServer struct {
}

func (*UnimplementedSmsServiceServer) QueueSend(ctx context.Context, req *SmsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueSend not implemented")
}

func RegisterSmsServiceServer(s *grpc.Server, srv SmsServiceServer) {
	s.RegisterService(&_SmsService_serviceDesc, srv)
}

func _SmsService_QueueSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).QueueSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.sms.SmsService/QueueSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).QueueSend(ctx, req.(*SmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "staffjoy.sms.SmsService",
	HandlerType: (*SmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueSend",
			Handler:    _SmsService_QueueSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms.proto",
}
