package(default_visibility = ["//visibility:public"])

load("//tools:build_rules/go.bzl", "go_library")

go_library(
    name = "healthcheck",
    srcs = [
        "healthcheck.go",
    ],
    deps = [],
)
