apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www-container
        image: localhost:5000/www:VERSION
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: SUITE_API_KEY
          value: staffjoydev
        - name: SIGNING_SECRET
          value: QqvNDpRMnDvuDZL2xCtVwdNPEX2jYhKyzuX3VzQEdfmruNNysxVRGdWXuin6jhdQ
        - name: RECAPTCHA_PUBLIC
          value: S3CrEtApIkEy
        - name: RECAPTCHA_PRIVATE
          value: S3CrEtApIkEy-
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
