package(default_visibility = ["//visibility:public"])

load("//tools:build_rules/go.bzl", "go_library")

go_library(
    name = "services",
    srcs = [
        "services.go",
    ],
    deps = [
    ],
)
