// Code generated by protoc-gen-gogo.
// source: bot.proto
// DO NOT EDIT!

/*
	Package bot is a generated protocol buffer package.

	It is generated from these files:
		bot.proto

	It has these top-level messages:
		OnboardWorkerRequest
		AlertNewShiftRequest
		AlertNewShiftsRequest
		AlertRemovedShiftRequest
		AlertRemovedShiftsRequest
		AlertChangedShiftRequest
*/
package bot

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import staffjoy_company "v2.staffjoy.com/company"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OnboardWorkerRequest struct {
	CompanyUuid string `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`
	UserUuid    string `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
}

func (m *OnboardWorkerRequest) Reset()                    { *m = OnboardWorkerRequest{} }
func (m *OnboardWorkerRequest) String() string            { return proto.CompactTextString(m) }
func (*OnboardWorkerRequest) ProtoMessage()               {}
func (*OnboardWorkerRequest) Descriptor() ([]byte, []int) { return fileDescriptorBot, []int{0} }

type AlertNewShiftRequest struct {
	UserUuid string                  `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	NewShift *staffjoy_company.Shift `protobuf:"bytes,2,opt,name=new_shift,json=newShift" json:"new_shift,omitempty"`
}

func (m *AlertNewShiftRequest) Reset()                    { *m = AlertNewShiftRequest{} }
func (m *AlertNewShiftRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertNewShiftRequest) ProtoMessage()               {}
func (*AlertNewShiftRequest) Descriptor() ([]byte, []int) { return fileDescriptorBot, []int{1} }

func (m *AlertNewShiftRequest) GetNewShift() *staffjoy_company.Shift {
	if m != nil {
		return m.NewShift
	}
	return nil
}

type AlertNewShiftsRequest struct {
	UserUuid  string                    `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	NewShifts []*staffjoy_company.Shift `protobuf:"bytes,2,rep,name=new_shifts,json=newShifts" json:"new_shifts,omitempty"`
}

func (m *AlertNewShiftsRequest) Reset()                    { *m = AlertNewShiftsRequest{} }
func (m *AlertNewShiftsRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertNewShiftsRequest) ProtoMessage()               {}
func (*AlertNewShiftsRequest) Descriptor() ([]byte, []int) { return fileDescriptorBot, []int{2} }

func (m *AlertNewShiftsRequest) GetNewShifts() []*staffjoy_company.Shift {
	if m != nil {
		return m.NewShifts
	}
	return nil
}

type AlertRemovedShiftRequest struct {
	UserUuid string                  `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OldShift *staffjoy_company.Shift `protobuf:"bytes,2,opt,name=old_shift,json=oldShift" json:"old_shift,omitempty"`
}

func (m *AlertRemovedShiftRequest) Reset()                    { *m = AlertRemovedShiftRequest{} }
func (m *AlertRemovedShiftRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertRemovedShiftRequest) ProtoMessage()               {}
func (*AlertRemovedShiftRequest) Descriptor() ([]byte, []int) { return fileDescriptorBot, []int{3} }

func (m *AlertRemovedShiftRequest) GetOldShift() *staffjoy_company.Shift {
	if m != nil {
		return m.OldShift
	}
	return nil
}

type AlertRemovedShiftsRequest struct {
	UserUuid  string                    `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OldShifts []*staffjoy_company.Shift `protobuf:"bytes,2,rep,name=old_shifts,json=oldShifts" json:"old_shifts,omitempty"`
}

func (m *AlertRemovedShiftsRequest) Reset()                    { *m = AlertRemovedShiftsRequest{} }
func (m *AlertRemovedShiftsRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertRemovedShiftsRequest) ProtoMessage()               {}
func (*AlertRemovedShiftsRequest) Descriptor() ([]byte, []int) { return fileDescriptorBot, []int{4} }

func (m *AlertRemovedShiftsRequest) GetOldShifts() []*staffjoy_company.Shift {
	if m != nil {
		return m.OldShifts
	}
	return nil
}

type AlertChangedShiftRequest struct {
	UserUuid string                  `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OldShift *staffjoy_company.Shift `protobuf:"bytes,2,opt,name=old_shift,json=oldShift" json:"old_shift,omitempty"`
	NewShift *staffjoy_company.Shift `protobuf:"bytes,3,opt,name=new_shift,json=newShift" json:"new_shift,omitempty"`
}

func (m *AlertChangedShiftRequest) Reset()                    { *m = AlertChangedShiftRequest{} }
func (m *AlertChangedShiftRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertChangedShiftRequest) ProtoMessage()               {}
func (*AlertChangedShiftRequest) Descriptor() ([]byte, []int) { return fileDescriptorBot, []int{5} }

func (m *AlertChangedShiftRequest) GetOldShift() *staffjoy_company.Shift {
	if m != nil {
		return m.OldShift
	}
	return nil
}

func (m *AlertChangedShiftRequest) GetNewShift() *staffjoy_company.Shift {
	if m != nil {
		return m.NewShift
	}
	return nil
}

func init() {
	proto.RegisterType((*OnboardWorkerRequest)(nil), "staffjoy.bot.OnboardWorkerRequest")
	proto.RegisterType((*AlertNewShiftRequest)(nil), "staffjoy.bot.AlertNewShiftRequest")
	proto.RegisterType((*AlertNewShiftsRequest)(nil), "staffjoy.bot.AlertNewShiftsRequest")
	proto.RegisterType((*AlertRemovedShiftRequest)(nil), "staffjoy.bot.AlertRemovedShiftRequest")
	proto.RegisterType((*AlertRemovedShiftsRequest)(nil), "staffjoy.bot.AlertRemovedShiftsRequest")
	proto.RegisterType((*AlertChangedShiftRequest)(nil), "staffjoy.bot.AlertChangedShiftRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BotService service

type BotServiceClient interface {
	OnboardWorker(ctx context.Context, in *OnboardWorkerRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	AlertNewShift(ctx context.Context, in *AlertNewShiftRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	AlertNewShifts(ctx context.Context, in *AlertNewShiftsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	AlertRemovedShift(ctx context.Context, in *AlertRemovedShiftRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	AlertRemovedShifts(ctx context.Context, in *AlertRemovedShiftsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	AlertChangedShift(ctx context.Context, in *AlertChangedShiftRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type botServiceClient struct {
	cc *grpc.ClientConn
}

func NewBotServiceClient(cc *grpc.ClientConn) BotServiceClient {
	return &botServiceClient{cc}
}

func (c *botServiceClient) OnboardWorker(ctx context.Context, in *OnboardWorkerRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/staffjoy.bot.BotService/OnboardWorker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertNewShift(ctx context.Context, in *AlertNewShiftRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/staffjoy.bot.BotService/AlertNewShift", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertNewShifts(ctx context.Context, in *AlertNewShiftsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/staffjoy.bot.BotService/AlertNewShifts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertRemovedShift(ctx context.Context, in *AlertRemovedShiftRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/staffjoy.bot.BotService/AlertRemovedShift", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertRemovedShifts(ctx context.Context, in *AlertRemovedShiftsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/staffjoy.bot.BotService/AlertRemovedShifts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AlertChangedShift(ctx context.Context, in *AlertChangedShiftRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/staffjoy.bot.BotService/AlertChangedShift", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BotService service

type BotServiceServer interface {
	OnboardWorker(context.Context, *OnboardWorkerRequest) (*google_protobuf.Empty, error)
	AlertNewShift(context.Context, *AlertNewShiftRequest) (*google_protobuf.Empty, error)
	AlertNewShifts(context.Context, *AlertNewShiftsRequest) (*google_protobuf.Empty, error)
	AlertRemovedShift(context.Context, *AlertRemovedShiftRequest) (*google_protobuf.Empty, error)
	AlertRemovedShifts(context.Context, *AlertRemovedShiftsRequest) (*google_protobuf.Empty, error)
	AlertChangedShift(context.Context, *AlertChangedShiftRequest) (*google_protobuf.Empty, error)
}

func RegisterBotServiceServer(s *grpc.Server, srv BotServiceServer) {
	s.RegisterService(&_BotService_serviceDesc, srv)
}

func _BotService_OnboardWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).OnboardWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/OnboardWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).OnboardWorker(ctx, req.(*OnboardWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertNewShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertNewShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertNewShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertNewShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertNewShift(ctx, req.(*AlertNewShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertNewShifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertNewShiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertNewShifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertNewShifts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertNewShifts(ctx, req.(*AlertNewShiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertRemovedShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRemovedShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertRemovedShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertRemovedShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertRemovedShift(ctx, req.(*AlertRemovedShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertRemovedShifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRemovedShiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertRemovedShifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertRemovedShifts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertRemovedShifts(ctx, req.(*AlertRemovedShiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AlertChangedShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertChangedShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AlertChangedShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staffjoy.bot.BotService/AlertChangedShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AlertChangedShift(ctx, req.(*AlertChangedShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BotService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "staffjoy.bot.BotService",
	HandlerType: (*BotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnboardWorker",
			Handler:    _BotService_OnboardWorker_Handler,
		},
		{
			MethodName: "AlertNewShift",
			Handler:    _BotService_AlertNewShift_Handler,
		},
		{
			MethodName: "AlertNewShifts",
			Handler:    _BotService_AlertNewShifts_Handler,
		},
		{
			MethodName: "AlertRemovedShift",
			Handler:    _BotService_AlertRemovedShift_Handler,
		},
		{
			MethodName: "AlertRemovedShifts",
			Handler:    _BotService_AlertRemovedShifts_Handler,
		},
		{
			MethodName: "AlertChangedShift",
			Handler:    _BotService_AlertChangedShift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}

func init() { proto.RegisterFile("bot.proto", fileDescriptorBot) }

var fileDescriptorBot = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0xaf, 0xd2, 0x40,
	0x14, 0xc5, 0x2d, 0x18, 0x43, 0x2f, 0x60, 0xe2, 0x04, 0x04, 0x61, 0x83, 0x63, 0xa2, 0xae, 0x86,
	0x04, 0x8d, 0x7b, 0x31, 0x2e, 0x95, 0x04, 0x82, 0x24, 0x6e, 0x48, 0x4b, 0xa7, 0x50, 0x6d, 0x7b,
	0x6b, 0x67, 0x0a, 0x61, 0xeb, 0x57, 0x79, 0x5f, 0xf4, 0xa5, 0xff, 0x08, 0xf3, 0xe8, 0x2b, 0x65,
	0xf1, 0x96, 0xed, 0xbd, 0xf7, 0x77, 0xee, 0xc9, 0x9c, 0x0b, 0xba, 0x89, 0x92, 0x05, 0x21, 0x4a,
	0x24, 0x2d, 0x21, 0x0d, 0xdb, 0xfe, 0x83, 0x47, 0x66, 0xa2, 0x1c, 0x0c, 0xb7, 0x88, 0x5b, 0x97,
	0x8f, 0x93, 0x9a, 0x19, 0xd9, 0x63, 0xee, 0x05, 0xf2, 0x98, 0xb6, 0x0e, 0xda, 0x1b, 0xf4, 0x02,
	0xc3, 0xcf, 0x3e, 0xe9, 0x2f, 0xe8, 0xcc, 0x7c, 0x13, 0x8d, 0xd0, 0x5a, 0x61, 0xf8, 0x97, 0x87,
	0x73, 0xfe, 0x2f, 0xe2, 0x42, 0x92, 0xb7, 0xd0, 0xca, 0x1a, 0xd7, 0x51, 0xe4, 0x58, 0x7d, 0x6d,
	0xa4, 0x7d, 0xd4, 0xe7, 0xcd, 0xec, 0xdf, 0x32, 0x72, 0x2c, 0x32, 0x04, 0x3d, 0x12, 0x3c, 0x4c,
	0xeb, 0xb5, 0xa4, 0xde, 0x88, 0x7f, 0xc4, 0x45, 0xea, 0x40, 0xe7, 0xab, 0xcb, 0x43, 0xf9, 0x93,
	0x1f, 0x16, 0x3b, 0xc7, 0x96, 0x39, 0x57, 0x19, 0xd2, 0xd4, 0x21, 0xf2, 0x19, 0x74, 0x9f, 0x1f,
	0xd6, 0x22, 0x1e, 0x48, 0x88, 0xcd, 0x49, 0x8f, 0x9d, 0xac, 0xe5, 0x8b, 0xa7, 0xbc, 0x86, 0x9f,
	0x91, 0xa9, 0x0b, 0x5d, 0x45, 0x4a, 0x54, 0xd2, 0xfa, 0x02, 0x70, 0xd2, 0x12, 0xfd, 0xda, 0xa8,
	0x5e, 0x26, 0xa6, 0xe7, 0x62, 0x82, 0x7a, 0xd0, 0x4f, 0xd4, 0xe6, 0xdc, 0xc3, 0x3d, 0xb7, 0x6e,
	0x32, 0x87, 0xae, 0x55, 0xd1, 0x1c, 0xba, 0x29, 0x99, 0x06, 0xf0, 0xe6, 0x42, 0xae, 0xb2, 0xc1,
	0x93, 0xde, 0x75, 0x83, 0xb9, 0xa0, 0xa0, 0x77, 0x5a, 0xe6, 0xf0, 0xdb, 0xce, 0xf0, 0xb7, 0x4f,
	0xee, 0x50, 0x7d, 0xf4, 0x7a, 0xc5, 0x47, 0x9f, 0xfc, 0x7f, 0x0e, 0x30, 0x45, 0xb9, 0xe0, 0xe1,
	0xde, 0xd9, 0x70, 0xf2, 0x03, 0xda, 0x4a, 0x8c, 0x09, 0x65, 0xe7, 0x27, 0xc1, 0x8a, 0x32, 0x3e,
	0x78, 0xcd, 0xd2, 0x43, 0x61, 0xf9, 0xa1, 0xb0, 0xef, 0xf1, 0xa1, 0xd0, 0x67, 0x31, 0x4e, 0x89,
	0xd4, 0x43, 0x5c, 0x51, 0xb4, 0x4b, 0x70, 0x33, 0x78, 0xa9, 0x26, 0x94, 0xbc, 0x2b, 0xe1, 0x89,
	0xeb, 0xc0, 0x25, 0xbc, 0xba, 0x48, 0x05, 0x79, 0x5f, 0xc0, 0x2c, 0x48, 0x69, 0x09, 0x76, 0x05,
	0xe4, 0x32, 0x6c, 0xe4, 0xc3, 0x15, 0xee, 0x0d, 0xfb, 0x9e, 0x47, 0xaa, 0x70, 0xdf, 0x82, 0xcc,
	0x3d, 0x8e, 0x9d, 0xf6, 0x7e, 0x77, 0x37, 0x68, 0x71, 0x25, 0x2d, 0x63, 0x13, 0xa5, 0xf9, 0x22,
	0x69, 0xfd, 0x74, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x26, 0x88, 0xe8, 0xf9, 0x23, 0x05, 0x00, 0x00,
}
